name: Docker Release

on:
  push:
    branches:
      - 'test'
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Docker
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build and Release Image
        shell: bash
        run: |
          set -x
          CURL=$(curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest)
          echo "$CURL"
          GREP=$(grep '"name": "kustomize/v' <<< "$CURL")
          echo $GREP

          if [ -z "$GREP" ]
          then
            echo "no new kustomize version."
            exit 0
          fi

          echo "NEW kustomize version."

          CUT=$(cut -d '"' -f 4 <<< "$GREP")
          echo $CUT
          KUSTOMIZE_VERSION=$(sed 's/kustomize\///g' <<< "$CUT")
          echo KUSTOMIZE_VERSION
          KUBECTL_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
          VERSION="kustomize-${KUSTOMIZE_VERSION}_kubectl-${KUBECTL_VERSION}"
          docker build -t smartive/kustomize:latest .
          docker tag smartive/kustomize:latest smartive/kustomize:$VERSION
          docker push smartive/kustomize:latest
          docker push smartive/kustomize:$VERSION